# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3585a732d741bba4f9ebd5acc2583adaf90e6a74997b8a871c1de976e499b5db52715431fa23afdb27cb251cd4d221fee1ad35f06e84fc1cd4bcccba22fb6595

test:
  secret_key_base: d542ad91619caf9a7cc06f1c8532a7695163458cbfc9ac6277c3348aea7057f3f225fa2e6eb962de50a9eab4e8681f30970896292678d68cf4d4d0a1ff601322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
